// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgSfRdmVRK7_pz_UKUgk4DZs8aU3w7wWw',
    appId: '1:51022022838:web:e280ebe35fa8fe3f83be17',
    messagingSenderId: '51022022838',
    projectId: 'auth-4c5f2',
    authDomain: 'auth-4c5f2.firebaseapp.com',
    databaseURL: 'https://auth-4c5f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auth-4c5f2.appspot.com',
    measurementId: 'G-ZLG20Q7V7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4KsXbhrYqloDjIp5miQnz6Y3giDkZIEA',
    appId: '1:51022022838:android:221eaf0a0b02eba083be17',
    messagingSenderId: '51022022838',
    projectId: 'auth-4c5f2',
    databaseURL: 'https://auth-4c5f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auth-4c5f2.appspot.com',
  );
}
